name: Nicolas Vinuesa
author: Nicolas Vinuesa
markdown: kramdown
highlighter: pygments
github: https://www.github.com/underscorenico
about: Hi! I'm an engineer with varied interests like signal processing, functional programming, theoretical computer science, distributed computing. On top of all i'm a huge football fan and proud supporter of Newell's Old Boys (Rosario, ARG).
gems:
  - jekyll-mentions
